---
title: "To do"
author: "Jenny Sjaarda"
date: "2021-09-08"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

# 06/09/2021

- ~~Sum $\rho$ and $\gamma$.~~
- ~~Meta-analyzed binned results across sexes.~~ 
- ~~Fix variance calculation mistake in calculating $\rho$ and $\gamma$.~~
- ~~Write script/function which replaces `Neale_ID` with trait description.~~
- ~~Clean up `index.Rmd`~~
- ~~Clean up `about.Rmd`~~
- Add Rmd building to `targets` pipeline. 
- MVMR. 
- ~~AM MR summary Rmd (and publish).~~
- ~~PC correlation among couples summary Rmd.~~ 
- ~~Clean up update meeting Rmd.~~
  - ~~14-06-21~~
  - ~~05-07-21~~
  - ~~14-07-21~~
  - ~~25-08-21~~
  - ~~06-09-21~~
- ~~Delete latex_test docs.~~

# 08/09/2021

- ~~Weight trend line by inverse variance.~~ 
- ~~Update AF in Neale summary stats.~~
- ~~Create couple selection Rmd.~~ 
- ~~Number of tests for filtering by $\omega$ should exclude those with only one trait. (i.e. number of tests would be $j^2 - j$).~~
- ~~Filter by $\omega$ instead of same-person MR.~~ 
- Force intercept through 0 in omega vs gamma/rho plot. 
- Explore impact of meta-anlaysis at SNP/trait level vs. MR-level.
  - Meta-analyze standard MR SNP/trait estimates across sexes. 
- Hierarchy figure (add labels).
- ~~Make visio figures in LucidChart.~~
- ~~Explore IV overlap between X and Y:~~
    - ~~Determine percentage of IV overlap between X IVs and Y IVs.~~ 
    - ~~MV MR, add SNPs/trait effect from $X_{i} \rightarrow Y_{p}$ to $Y_{i} \rightarrow Y_{p}$ MR (i.e. run a MV MR of the form: $Y_{p} \sim Y_{i} + X_{i}$).~~
- ~~Add script/function which replaces `Neale_ID` with trait description to main functions.~~
- Add status notebook, largely copied from here (https://github.com/rgayler/fa_sim_cal/blob/master/analysis/m_00_status.Rmd).

# 15/09/2021

- ~~Clean up figures for group meeting presentation Rmd.~~
- ~~Delete RData and rds files.~~
- MR between partners (partner vs index) Rmd (can take a lot from early July update meeting).
- MR within same individual Rmd (can take a lot from August update meeting).
- Compare paths towards outcome in partner Rmd  (can take a lot from August update meeting).
- ~~Rerun het figures and AM MR summary.~~
- ~~Add pipeline_overview.Rmd.~~

## 24/09/2021

- PC analysis
    - Draw a DAG for this, confirm with Zoltan. 
- ~~Delete `binary_added.csv` file.~~
- ~~Remove left body trait, dietary traits, re-add binary traits.~~
- ~~In 2 trait model, restrict to only variables with correlation < 0.8 (play with this a bit until we see that traits are really different).~~
- ~~Also include X IVs in adjYiYp models in addition to Y IVs.~~
- Check which unrelated group was using in PC GWAS. 


