---
title: "Update Meeting: 29-11-2021"
author: "Jenny Sjaarda"
date: "2021-11-01"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r setup, include = FALSE}

options(scipen=999)
source("code/settings.R")
source("R/functions.R")
library(targets)
library(dplyr)
library(DT)
library(knitr)
library(ggplot2)
library(kableExtra)
library(cowplot)
library(plotly)
```

```{r load_targets, include = FALSE, eval = ifelse(Sys.info()["sysname"]=="Linux", TRUE, FALSE)}
tar_load(couple_MR_vs_trait_corr)
tar_load(corr_impact_by_traits)

```

# Analyses update.

## MR effects vs. raw correlation.

```{r corr_vs_MR_effects, echo = FALSE, eval = ifelse(Sys.info()["sysname"]=="Linux", TRUE, FALSE), message=FALSE}

plot_data <- couple_MR_vs_trait_corr %>% dplyr::select(IVW_beta_std, couple_r)

plot <- ggplot2::ggplot(data = plot_data, ggplot2::aes(x = couple_r,
                                                       y = IVW_beta_std)) +
  geom_point(alpha = 3/4) +
  
  geom_abline(slope=1, intercept=0) +
  
  theme_minimal() +
  ggplot2::labs(x = paste0("Couple correlation"),
                y = paste("Standardized MR effect"))

plot 

ggplotly(plot)
```

## Re-calculate number of significance in same trait analyses. 

## Compare male and female effects. 

## Confounder analysis with added variables. 

## Repeat hierarchical plot. 



